### ISSUE TITLE
FTLOG

### ISSUE THREAD

**Issue by ORESoftware** [Polymer/observe-js#101]
FTLOG please put installation instructions for this lib

do we use npm?
bower?
something else?

keeping me guessing

**Comment by ORESoftware** [comment]
in fact it does work with bower

CACSVML-13295:sc-admin-ui-express amills001c$ bower install observe-js
bower observe-js#*          not-cached git://github.com/Polymer/observe-js.git#*
bower observe-js#*             resolve git://github.com/Polymer/observe-js.git#*
bower observe-js#*            download https://github.com/Polymer/observe-js/archive/0.5.6.tar.gz
bower observe-js#*             extract archive.tar.gz
bower observe-js#*            resolved git://github.com/Polymer/observe-js.git#0.5.6
bower observe-js#~0.5.6        install observe-js#0.5.6

observe-js#0.5.6 bower_components/observe-js
CACSVML-13295:sc-admin-ui-express amills001c$ 


please put this as the first thing in the docs, thank you!!

**Comment by jmesserly** [comment]
we don't maintain the copies of the code that people have uploaded to various pkg managers. sorry.

**Comment by ORESoftware** [comment]
thanks, I see hmm
