### ISSUE TITLE
Is this supposed to work?

### ISSUE THREAD

**Issue by benknight** [Polymer/observe-js#112]
I copied the examples proved in the README into my Firefox console and the observer callback wasn't getting called at all.  I believe it's the same case in Safari.  Chrome is the only browser executing the observer callback.  Am I doing something wrong here?

**Comment by jmesserly** [comment]
https://github.com/Polymer/observe-js#about-delivery-of-changes

Unless your browser has native Object.observe support, it's up to you to figure out what frequency to check for changes.

I answered a similar question here:
https://github.com/Polymer/observe-js/issues/98#issuecomment-134657269

**Comment by benknight** [comment]
Ah, I see.  My bad, somehow I totally blew over this section of the README.  Thanks!  :palm_tree:

**Comment by benknight** [comment]
I might suggest referencing this section elsewhere in the readme as it's fairly easy to miss.  Something like your plain English reply to me in this thread somewhere high-up and relevant couldn't hurt. Thanks again.
