### ISSUE TITLE
version on npm is 0.4.2 while releases here on github show latest as 0.5.6

### ISSUE THREAD

**Issue by capaj** [Polymer/observe-js#114]
which one is it? Can't you have the same version in both github and npm like every other project?

**Comment by ebidel** [comment]
I think publishing to npm has been neglected.

**Comment by mickaelvalmier** [comment]
+1

**Comment by mickaelvalmier** [comment]
Yes, version in NPM is outdated, it's annoying when we would to use this awesome library with browserify !
It's possible to update ?

Regards

**Comment by jmesserly** [comment]
it looks like @azakus has permissions to publish:
https://www.npmjs.com/package/observe-js

**Comment by dfreedm** [comment]
Published 0.5.7 to npm

**Comment by c3riz88** [comment]
Thanks for your responsiveness !
