### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by felixlaumon** [Polymer/observe-js#20]
Hi @rafaelw, I'm wondering what's the status of this project? Is ChangeSummary kind of production-ready? I'd like to use it like a Object.observe shim. I understand I will still need to call `.deliver()` but this project seems to be more promising than any other shim I have seen so far.

Thanks again for this awesome project! Please let me know :D

**Comment by QuantumInformation** [comment]
So if this is not designed as a shim for Object.observe what is the best library out there for using as a shim?

**Comment by jmesserly** [comment]
> So if this is not designed as a shim for Object.observe what is the best library out there for using as a shim?

I'm confused ... it says above (emphasis mine):

> Using this project as a shim for Object.observe is *exactly* it's intent. It uses Object.observe if present and dirty-checks if not.
