### ISSUE TITLE
Observations not triggered for defined properties in Chrome?

### ISSUE THREAD

**Issue by mtford90** [Polymer/observe-js#78]
i.e. the following test fails:

```js
it('property', function (done) {
    var obj = { foo: { bar: 'baz' } };
    Object.defineProperty(obj, 'prop', {
        get: function () {
            return this.foo.bar.toUpperCase();
        },
        enumerable: true,
        configurable: true
    });
    var observer = new PathObserver(obj, 'prop');
    observer.open(function(newValue, oldValue) {
        assert.equal(newValue, 'TEST');
        assert.equal(oldValue, 'BAZ');
        done();
    });
    obj.foo.bar = 'test';
    Platform.performMicrotaskCheckpoint();
});
```

This works in firefox & safari e.g. via dirty checks but fails in Chrome. So I'm guessing this is something to do with `Object.observe`?

**Comment by rafaelw** [comment]
Yes, that is expected with Object.observe. In this example, you've created a "computed" property ('prop') whose value is dependent on 'foo.bar'. There are two problems in your code:

1) Accessors are never automatically observable. They must broadcast when they change, using Object.getNotifier(obj).notify(/* changeRecord */).

2) The computed property you've setup has no way of knowing when it's dependent value ('foo.bar') changes.

**Comment by mtford90** [comment]
Suspected so, had no idea about `Object.getNotifier(obj).notify(/* changeRecord */).` so thanks for that.

Have a good one.

**Comment by mtford90** [comment]
Hang on a sec tho - I can't help but think that this should be consistent across browsers? It should either work or it should not... If it doesn't work with `Object.observe` then it shouldn't work with the dirty check. Does `Object.getNotifier(obj).notify(/* changeRecord */).` do nothing if `Object.observe` is not available?

**Comment by rafaelw** [comment]
Yeah, I agree actually -- which really means that it *shouldn't work* under dirty-checking. However, implementing this is infeasible as it would create a bunch of additional perf overhead for the dirty-checking-path. As dirty-checking is really the cheat which is trying to get us to the Object.observe world, it's something we have to live with.

Object.getNotifier() is a part of the Object.observe API. You should create notification code that is a no-op if Object.observe is absent. You can see polymer doing this here

https://github.com/Polymer/polymer-dev/blob/master/src/instance/properties.js#L152
