### ISSUE TITLE
PathObserver ignores property names with hyphens

### ISSUE THREAD

**Issue by pflannery** [Polymer/observe-js#79]
I've found that property names with hyphens get rejected [at this stage](https://github.com/Polymer/observe-js/blob/master/src/observe.js#L284)

[example](http://plnkr.co/edit/olBwbzyr5KILP2o3mMX2?p=preview)

```js
    var obj = {
      child: {
        "some-property": 123
      }
    };

    var obs = new PathObserver(obj, "child.some-property"); // child['some-property'] // will work
    obs.open(function(newVal, oldVal) {
      // never gets called upon change
    })
```

I found that wrapping properties with hyphens in ['some-property'] works but that means we would have to reformat the whole path before we can observe them.
is there a better way?

**Comment by rafaelw** [comment]
`The intent here is to be consistent with ECMAScript syntax (e.g. `var foo = child.some-property` would result in a syntax error in js). Member access (e.g. ".foo") is only supported for valid identifiers. Non-identifiers are supported via quotation

**Comment by pflannery** [comment]
Just seems strange when it's already quoted by the string.

**Comment by jmesserly** [comment]
problem is it could be ambiguous when you consider something like https://github.com/Polymer/polymer-expressions ... if PathObserver started parsing `child.some-property` as `child['some-property']` it would rule out the interpretation: `child.some - property`. So it stays out of the expression business and keeps PathObserver to a simple identifier sequence.

**Comment by pflannery** [comment]
ok I understand. thanks for your reply.
