### ISSUE TITLE
invalidPath returned when using number-like keys for adding a path observer

### ISSUE THREAD

**Issue by jjwill** [Polymer/observe-js#86]
I am running into an issue where this.path_ is always undefined for a PathObserver where the key is a number-like string. The transition here, https://github.com/Polymer/observe-js/blob/0.4.0/src/observe.js#L286, always returns 'error' because the type var above is 'number'. 

Changing obj will never trigger the changeFn:

```
var obj = {'1': 'one'};
var observer = new PathObserver(obj, '1');  
observer.open(changeFn, context); // some callback and scope
```

**Comment by OlsonDev** [comment]
I don't think your path is technically supported. However, here's a workaround:

```JavaScript
let obj = { '1': 'one' };
let observer = new PathObserver(obj, '[1]');
observer.open(console.log.bind(console));
obj[1] = 'two'; // console logs: two one PathObserver{ ... }
```

**Comment by jjwill** [comment]
Ahh, good call; thanks for the workaround @OlsonDev.
