### ISSUE TITLE
Can't reopen a closed observer

### ISSUE THREAD

**Issue by bensleveritt** [Polymer/observe-js#91]
I'm not sure if this is intended, but trying to reopen a closed observer throws the error `Observer has already been opened.`

Is it best just to remove the observer completely and reinitialise?

**Comment by jmesserly** [comment]
> Is it best just to remove the observer completely and reinitialise?

exactly right, it's not intended to re-open a closed observer. think of "close" like a "dispose" ... it's called when the observer is no longer need. (As an optimization, the system will try to reuse observer instances, which is probably why you got that error message. Look for `observedObjectCache` in the code.)

**Comment by bensleveritt** [comment]
Thanks for the clarification!
