### ISSUE TITLE
PathObserver only get called in Chrome

### ISSUE THREAD

**Issue by woeldiche** [Polymer/observe-js#92]
Trying to use PathObserver, we're seeing an issue where the changeFn only get's executed in Chrome (42), but not Safari (8.x) or Firefox (37.x).

Using both custom code and the example code from github.com/Polymer/observe-js gives the same result: The observer seem to be opened correctly, but the changeFn only executes in Chrome.

Logging the observer returns apparently identical objects in both Chrome and Safari, including the object, original values and callback function.

The issue seems to be consistent across the projects where we are attempting to use observe-js. 
We're loading Observe-js 0.4.2 using npm.

AFAIK this at least correlates with Chrome being the only browser with native support for Object.observe.

**Comment by markomanninen** [comment]
I was just experiencing same issue. I was supposing library should work with recent Safari and Firefox versions.

**Comment by woeldiche** [comment]
Object.observe should return false in Safari and Chrome, since they don't implement it natively. But I was under the impression that observe-js would act as a polyfill?

**Comment by markomanninen** [comment]
Yeha, it was my mistake, I was using observe-api by http://jwsdev.net/TipSheet/scripts/observe-api.js and had to change the order of the scripts and solve race dilemma. But even then problem for same browsers stays...

**Comment by jmesserly** [comment]
Hello @woeldiche, it sounds like you need: https://github.com/Polymer/observe-js#about-delivery-of-changes

In particular, only V8/Chrome implements the ES7 draft Object.observe behavior. For all other browsers and JS engines, you need to call `Platform.performMicrotaskCheckpoint()`. For example, here's how the tests do it:
https://github.com/Polymer/observe-js/blob/master/tests/test.js#L16

**Comment by woeldiche** [comment]
Thank you and for the example. Closing the issue :-)
