### ISSUE TITLE
ObjectObserver doesn't seem to work in Safari iOS

### ISSUE THREAD

**Issue by pshihn** [Polymer/observe-js#98]
I'm using the object observer to detect when new members are being added to an object. This used to work on Chrome when I was using the observe-js that came with Polymer 0.5

Now, with latest observe-js, I am trying the same thing on Safari on iOS. I don't get called back when new members are added to the object.

**Comment by cleverplatypus** [comment]
Confirmed. I'm extensively using PathObserver too for a big project but it doesn't seem to work on the desktop version of Safari (Yosemite).

Pity

**Comment by jmesserly** [comment]
observe-js doesn't work automatically in browsers without native Object.observe support. You need to call `Platform.performMicrotaskCheckpoint()`. See https://github.com/Polymer/observe-js#about-delivery-of-changes.

The exact policy of when to call it is up to you. Some projects just use polling and setTimeout, some use Zones: https://github.com/btford/zone.js, some just call it manually after they changed something.

**Comment by jmesserly** [comment]
Polymer 0.5 sets up polling, FWIW.
